### ISSUE TITLE
Monitor multiple SMSC 

### ISSUE THREAD

**Issue by icepicknz** [apostvav/kannel_exporter#18]
I have fired up two kannel_exporters for the two SMSC's we have

```
  - job_name: smsc02
    static_configs:
    - targets: ['localhost:9390']
  - job_name: smsc03
    static_configs:
    - targets: ['localhost:9391']

```

Is this the correct way of doing it?
I'm guessing from the example dashboard for grafana it will all go into the single dashboard, with no way to tell which SMSC the stats are for?
